---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-media-stack
resources:
  - ingress.yaml
  - service.yaml
  - namespace.yaml
