# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: config-map-external-secrets-homeserver-config
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: vault-backend-cross-namespaces-configmap
#     kind: ClusterSecretStore
#   target:
#     name: matrix-synapse
#     template:
#       engineVersion: v2
#       templateFrom:
#       - configMap:
#           # name of the configmap to pull in
#           name: matrix-synapse2
#           items:
#           - key: homeserver.yaml
#   dataFrom:
#     - extract:
#         key: synapse/homeserver
# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: config-map-external-secrets-whatsapp-config
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: vault-backend-cross-namespaces-configmap
#     kind: ClusterSecretStore
#   target:
#     name: matrix-bridge-whatsapp-config2
#     template:
#       engineVersion: v2
#       templateFrom:
#       - configMap:
#           # name of the configmap to pull in
#           name: matrix-bridge-whatsapp-config2
#           items:
#           - key: config.yaml
#   dataFrom:
#     - extract:
#         key: synapse/whatsapp-cfg
#     - extract:
#         key: synapse/homeserver
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-credentials-file
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-cross-namespaces-secret
    kind: ClusterSecretStore
  target:
    name: aws-credentials-file
    template:
      engineVersion: v2
      data:
        credentials: |
          [default]
          AWS_REGION=us-west-1
          AWS_ACCESS_KEY_ID={{ .access_key_id }}
          AWS_SECRET_ACCESS_KEY={{ .secret_access_key }}
  dataFrom:
    - extract:
        key: matrix-synapse/minio-s3-backup-secret
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-cross-namespaces-secret
    kind: ClusterSecretStore
  target:
    name: aws-credentials
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_access_key }}"
  dataFrom:
    - extract:
        key: matrix-synapse/minio-s3-backup-secret
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-bucket-storage
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend-cross-namespaces-secret
    kind: ClusterSecretStore
  target:
    name: aws-bucket-storage
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .aws_secret_access_key }}"
        S3_ENDPOINT: "{{ .endpoint_url }}"
        s3-storage-provider.yaml: |
          media_storage_providers:
          - module: s3_storage_provider.S3StorageProviderBackend
            store_local: True
            store_remote: True
            store_synchronous: false
            config:
              bucket: {{ .bucket }}
              prefix: {{ .bucket_prefix }}
              endpoint_url: {{ .endpoint_url }}
              region_name: us-west-1
              access_key_id: {{ .aws_access_key_id }}
              secret_access_key: {{ .aws_secret_access_key }}
        db.yaml: |
         database:
          name: psycopg2
          txn_limit: 10000
          args:
            user: {{ .username }}
            password: {{ .password }}
            database: synapse
            host: matrix-pg-synapse-rw
            port: 5432
            cp_min: 5
            cp_max: 10
        oidc.yaml: |
          oidc_providers:
          - idp_id: "{{ .idp_id }}"
            idp_name: "KeyCloak"
            enable_registration: true
            issuer: "{{ .issuer }}"
            client_id: "{{ .client_id }}"
            client_secret: "{{ .client_secret }}"
            scopes: ["openid", "profile"]
            user_mapping_provider:
              config:
                localpart_template: "{{`{{ user.preferred_username }}`}}"
                display_name_template: "{{`{{ user.name }}`}}"
                email_template: "{{`{{ user.email }}`}}"
            # attribute_requirements:
            #   - attribute: userGroup
            #     value: "synapseUsers"
            allow_existing_users: true
            backchannel_logout_enabled: true
        ratelimits.yaml: |
          rc_message:
            per_second: 100
            burst_count: 100
          rc_registration:
            per_second: 100
            burst_count: 100
          rc_registration_token_validity:
            per_second: 100
            burst_count: 100
          rc_login:
            address:
              per_second: 100
              burst_count: 100
            account:
              per_second: 100
              burst_count: 100
            failed_attempts:
              per_second: 100
              burst_count: 100
          rc_admin_redaction:
            per_second: 100
            burst_count: 100
          rc_joins:
            local:
              per_second: 100
              burst_count: 100
            remote:
              per_second: 100
              burst_count: 100
          rc_3pid_validation:
            per_second: 100
            burst_count: 100
          rc_invites:
            per_room:
              per_second: 100
              burst_count: 100
            per_user:
              per_second: 100
              burst_count: 100
          rc_third_party_invite:
            per_second: 100
            burst_count: 100
        observability.yaml: |
          opentracing:
            enabled: true
            homeserver_whitelist:
            - .*
            # force_tracing_for_users:
            # - '@user1:server_name'
            # - '@user2:server_name'
            jaeger_config:
              sampler:
                type: const
                param: 1
              logging: false
  dataFrom:
    - extract:
        key: matrix-synapse/s3-backup-secret
    - extract:
        key: matrix-synapse/postgres-synapse-user
    - extract:
        key: matrix-synapse/oidc
