---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-openebs-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: oebs-local-hostpath
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: storage-test-pod-hostpath
  labels:
    app: storage-test
spec:
  containers:
    - name: test-container
      image: busybox:1.38
      command:
        - sleep
        - "infinity"
      volumeMounts:
        - name: test-volume
          mountPath: /data
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-pvc-openebs-hostpath
  restartPolicy: Never
