---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-openebs-lvm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-lvm
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: storage-test-pod-lvm
  labels:
    app: storage-test
spec:
  containers:
    - name: test-container
      image: busybox:1.36
      command:
        - sleep
        - "infinity"
      volumeMounts:
        - name: test-volume
          mountPath: /data
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-pvc-openebs-lvm
  restartPolicy: Never
