apiVersion: v1
kind: Secret
metadata:
    name: wireguard-keys
type: Opaque
stringData:
    privateKey: ENC[AES256_GCM,data:ZvNV+fKpWyka6NYhOUWO03gWp56FU3QLpcGVjAhJumdMVpENx7Wo2DyNb30=,iv:5AjlWDb2nr2gItzATAw3vkNhYSIYWODz+Yw9vJkecP4=,tag:6oi6U6UY8O4Nvq+/y+kKtw==,type:str]
    publicKey: ENC[AES256_GCM,data:Uha7ARP6QrObuHxls3Rhy8ANiL2wXneZwP+o1jOFtDUQ2Qx694cNpO5lO1Y=,iv:zAghDI0HxSUmfWAYTZcT7zdt/OW6mXHBMxVL5i9Uo/k=,tag:efyTFDpZkfKOVuSoj7nfQQ==,type:str]
sops:
    age:
        - recipient: age1878n4cfsfpjqquszn2tlj0kq8ckwhdyx5eqjl32rh5vfs265gydq4myw6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYmZteWhHZGlGQnhrUUVr
            eENtaVVXb1BTelo5RktId24zNjJQTEpsR1hRClNTVlVRZjlPVzZmZHJScW16UThO
            SjF4ajdXM2pPZFFmODhBeXhFS09RdDgKLS0tIEhRNGhLZnI5eU9meVdjQldtMFNn
            S2JZMEZocUFjTElXeUlJRDExRWZnVVEKUT1p2j3B4O7cjVI8DC10PWVi04fuG3lA
            9iFyj1cxaByJn6CvfrnAc9vDjnZC+CyRp5ohJZQwrR9WiPpPMy1xzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T10:24:42Z"
    mac: ENC[AES256_GCM,data:fBr0nqDEpBIMbwxzCICeM3Jao5ircUmlgf7LPePe1UwvjaUtzFPR2Af/ah0IPgXau4pIyg7tlDvFxF+DUmZxJO9jEc8csy/fd4cjkVoCdRmPgiJaPfYRI0fQNE8F41LL9ozYC33R3ap5DG/09L4ZOXL9GEaXNMNRIG6/rXn3psk=,iv:7rdxP0Qoa5ZWTOEhA09cp9coMgNqa9UeOe+MaXn0XRM=,tag:ehISUccaJm22OToNd3YuEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
