---
apiVersion: v1
kind: Service
metadata:
  name: wireguard-vxlan
  labels:
    service-type/vxlan: static
  annotations:
    lbipam.cilium.io/ips: "10.129.16.201"
spec:
  # clusterIP: 10.43.255.250 ## only needed for fqdn nfs mounting, since it is not resolving in kubernetes manifests
  type: LoadBalancer
  selector:
    name: wireguard
  ports:
    - name: minio-api
      port: 9010
      targetPort: 9010
    - name: minio-ui
      port: 9011
      targetPort: 9011
