global:
  checkNewVersion: false
  sendAnonymousUsage: false
additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
# nodeSelector: # temp till secont node ingress is fixed, find out why
# kubernetes.io/hostname: rke2-local-node-01
api:
  dashboard: true
  disableDashboardAd: true
  insecure: true
deployment:
  enabled: true
  kind: Deployment
  replicas: 3
  terminationGracePeriodSeconds: 10
  minReadySeconds: 2
  podLabels:
    nat-policy: "enabled"
ingressClass:
  enabled: true
  isDefaultClass: true
  name: &ingress-class-name traefik-external
ingressRoute:
  dashboard:
    enabled: true
    # annotations:
    #   traefik.ingress.kubernetes.io/router.middlewares: network-oidc-auth@kubernetescrd
#       # traefik.ingress.kubernetes.io/router.entrypoints: websecure
#       # traefik.ingress.kubernetes.io/router.middlewares: network-traefik-dashboard-auth@kubernetescrd
    # matchRule: PathPrefix(`/`)
    matchRule: Host(`traefik.cloud.icylair.com`)
    entryPoints: ["websecure"]
    middlewares:
      - name: "forward-auth"
ports:
  traefik:
    port: 8001
  ts:
    port: 9987
    protocol: UDP
  websecure:
    http3:
      enabled: true
    proxyProtocol:
      trustedIPs:
        - "10.99.10.254"
        - "10.129.16.254"
        - "10.128.16.100"
      insecure: false
    # http:
    #   middlewares:
    #     - network-oidc-auth@kubernetescrd
gateway:
  listeners:
    web:
      namespacePolicy:
        from: All
    websecure:
      port: 8443
      hostname: "*.icylair.com"
      protocol: HTTPS
      namespacePolicy:
        from: All
      certificateRefs:
        - kind: Secret
          name: "icylair-com-all-prod"
service:
  single: true
  type: LoadBalancer
  annotations:
    lbipam.cilium.io/ips: "10.99.10.11,10.99.10.12,10.99.10.13,10.49.22.2,10.129.16.100"
  labels:
    service-type: ingress-static
    service-type/alt: wireguard-static
    service-type/vxlan: static
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true
  kubernetesGateway:
    enabled: true
    experimentalChannel: true
  kubernetesIngressNGINX:
    enabled: true
  file:
    enabled: true
    watch: true
rbac:
  enabled: true
tlsStore:
  default:
    defaultCertificate:
      secretName: icylair-com-all-prod

tracing:
  addInternals: true
  serviceName: traefik-cluster-prod
  otlp:
    enabled: true
    http:
      enabled: true
      endpoint: http://opentelemetry-collector.observability.svc.cluster.local:4318/v1/traces
metrics:
  # prometheus:
  #   serviceMonitor:
  #     enabled: true
  #   # prometheusRule:  # TODO this breaks it
  #   #   enabled: true
  otlp:
    enabled: true
    addRoutersLabels: true
    addServicesLabels: true
    http:
      enabled: true
      endpoint: http://opentelemetry-collector.observability.svc.cluster.local:4318/v1/metrics
# accessLog:
#   enabled: true
#   format: json
#   otlp:
#     grpc:
#       insecure: true
#       endpoint: opentelemetry-collector.observability.svc.cluster.local:4317/v1/logs

experimental:
  otlpLogs: true
  plugins:
    traefik-api-key-auth:
      moduleName: "github.com/Septima/traefik-api-key-auth"
      version: "v0.3.0"
    traefikoidc:
      moduleName: "github.com/lukaszraczylo/traefikoidc"
      version: v1.0.26

logs:
  general:
    format: json # "common", "json", null"
    level: INFO # levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.

resources:
  requests:
    memory: "100Mi"
    cpu: "30m"
  limits:
    memory: "6Gi"
    cpu: "3000m"
