---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaegertracing
spec:
  interval: 15m
  chart:
    spec:
      chart: jaeger
      version: 4.6.0
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    provisionDataStore:
      cassandra: false
    storage:
      type: memory
    agent:
      enabled: false
    collector:
      enabled: false
    query:
      enabled: false
    allInOne:
      enabled: true
      ingress:
        enabled: true
        # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
        # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
        ingressClassName: traefik-external
        # labels: {}
        # Used to create an Ingress record.
        hosts:
          - jaeger.cloud.icylair.com
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: network-forward-auth@kubernetescrd
        #   kubernetes.io/ingress.class: nginx
        #   kubernetes.io/tls-acme: "true"
        labels:
          app: jaeger
        tls:
          # Secrets must be manually created in the namespace.
          - secretName: icylair-com-all-prod
            hosts:
              - jaeger.cloud.icylair.com
---
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: grafanadatasource-jaeger
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  uid: jaeger
  datasource:
    name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaegertracing-query.observability.svc.cluster.local:16686
    jsonData:
      nodeGraph:
        enabled: true
      spanBar:
        type: None
      timeout: 15
      traceIdTimeParams:
        enabled: true
      tracesToLogsV2:
        customQuery: false
        datasourceUid: loki
        spanStartTimeShift: "1h"
        spanEndTimeShift: "-1h"
        tags: ["job", "instance", "pod", "namespace"]
        filterByTraceID: false
        filterBySpanID: false
        query: 'method="$${__span.tags.method}"'
      tracesToMetrics:
        datasourceUid: prometheus
        spanStartTimeShift: "1h"
        spanEndTimeShift: "-1h"
        tags:
          [{ key: "service.name", value: "service" }, { key: "job" }]
        queries:
          - name: "Sample query"
            query: "sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))"
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: "1h"
        spanEndTimeShift: "-1h"
