---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: xauth
resources:
  #https://www.keycloak.org/operator/installation
  - github.com/keycloak/keycloak-k8s-resources/kubernetes?ref=26.8.0


  - secret.yaml
  # - release.yaml
  - pg-keycloak.yaml
