apiVersion: v1
kind: Secret
metadata:
    name: keycloak-auth
type: Opaque
stringData:
    #ENC[AES256_GCM,data:rolaSibUKsN1d5TIwUNNrG59yMTom++vTTtpwobQjN4FTGJV1RTsY7qQWXLdkyQNFhwv+cjygSd6J8TiwpBQjZnPz5N9efiGB0vnAQSmw6Yx,iv:ffFxdOEI0Wm10lNt84fHQU2aMLKWWQYono+1+Tm1SV4=,tag:C+8d2JdD/rn7Cnaywjf3xg==,type:comment]
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:T9o2uzFiin+iRPoV,iv:RqxzMwh8x+Uxnl42L9YhRN3LhykwXNgNzCru37GuQno=,tag:ikYSzUPlEDhLnxLvV+FH5w==,type:str]
    host: ENC[AES256_GCM,data:KC2Fn+1ye1PrLoWHa8Q=,iv:SJVuwIP2n3tcHsIST2/35FmjcBVSwBY0qmYcJ4YXtQs=,tag:RATiKysSwj9gYdlxNcKJIw==,type:str]
    port: ENC[AES256_GCM,data:dDqBGg==,iv:aqzXw4NW/0kg2H1MKzJR2o2EUnfrrtRB/EgJeGBGbbY=,tag:a4VyDDffnf3bpUZ3Whop/w==,type:str]
    databse_name: ENC[AES256_GCM,data:qP31dilUp3OVdJY=,iv:ePs43FjPiZ6BXubka7uLzdlh8AY/fH9Hi1QnpyMWPuc=,tag:SBNA+aUcIp8Vx8wLLA6g+Q==,type:str]
    username: ENC[AES256_GCM,data:reWlXrVd6BA=,iv:FN0NWcRl7YSM/am+SJLz7YyBHcGHik9YHXMQPSDx3kM=,tag:SZu1pZSJ2eQ0b3dMFA5mVA==,type:str]
    password: ENC[AES256_GCM,data:rcLd6+7fJf9TB8Ex,iv:cPCMhbYDU6mGXQiuAq8ClNYKNFf+ypZzY5GyQGVVEjs=,tag:8t9Uq5LeJABjf83GzZk6UA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBM1NmSWRtT2xGN2F5TmVy
            OXpvUEZ3emtIdFV3cWFxWndGeURwYTBkSHdjCkpEWGFEa0FpSzVkNzVNQ2JRdVJw
            ZEJCOXlpUmpyY1dKSkJYbVlBQWhnT0UKLS0tIGpwNjd6eDJqckJSQUJJcXFoY1RC
            OXNsajQ5amx1NDIxbHZ1ZWFXamludW8KKxAI3NVLpBrUDrEUBNQsdSBQwcmemUhq
            pZFIX1+nfwsrG9wYyrn32uwSroCSVfW5rUyfdDWW0TqK/10yh0FTTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1878n4cfsfpjqquszn2tlj0kq8ckwhdyx5eqjl32rh5vfs265gydq4myw6a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T15:08:19Z"
    mac: ENC[AES256_GCM,data:iEHyrvRNjZo5+Bd1qVsNyh1fGb2UKFE5YbKI4kCDv7S/3x7Rmz1EqaJHGBu0U4p8IVduyQYbF1OpP9XCzj1OgmHlcylb2AkAUHp5eHXJzzzWBihcSVa5ACawSC+ZmFqB+GddsinYQLgun2aldlYoI4L0HPmd1ww0UyfzmKp5yH0=,iv:kKQKmGTusURW0i1S8RhOQ+3t3n6vUBpwOD8dTbrY6qU=,tag:8kCvD0oMuz1mDI0khmPLrg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-pg-superuser
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:qi1oaLAbnwE=,iv:ymkXzol2miF5pzSpGHgq7VteyO7kucAckjKjgXX64W8=,tag:5tDHqsET4YycWZWb1luGqg==,type:str]
    password: ENC[AES256_GCM,data:1UU1z4//2wEU+bIt,iv:CexQGRlsUXKEgD7KbE50gAPKkQBQkxrWSfr5k8vWBNk=,tag:uXkzzDvV3/lmQTFvTgAJRQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBM1NmSWRtT2xGN2F5TmVy
            OXpvUEZ3emtIdFV3cWFxWndGeURwYTBkSHdjCkpEWGFEa0FpSzVkNzVNQ2JRdVJw
            ZEJCOXlpUmpyY1dKSkJYbVlBQWhnT0UKLS0tIGpwNjd6eDJqckJSQUJJcXFoY1RC
            OXNsajQ5amx1NDIxbHZ1ZWFXamludW8KKxAI3NVLpBrUDrEUBNQsdSBQwcmemUhq
            pZFIX1+nfwsrG9wYyrn32uwSroCSVfW5rUyfdDWW0TqK/10yh0FTTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1878n4cfsfpjqquszn2tlj0kq8ckwhdyx5eqjl32rh5vfs265gydq4myw6a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T15:08:19Z"
    mac: ENC[AES256_GCM,data:iEHyrvRNjZo5+Bd1qVsNyh1fGb2UKFE5YbKI4kCDv7S/3x7Rmz1EqaJHGBu0U4p8IVduyQYbF1OpP9XCzj1OgmHlcylb2AkAUHp5eHXJzzzWBihcSVa5ACawSC+ZmFqB+GddsinYQLgun2aldlYoI4L0HPmd1ww0UyfzmKp5yH0=,iv:kKQKmGTusURW0i1S8RhOQ+3t3n6vUBpwOD8dTbrY6qU=,tag:8kCvD0oMuz1mDI0khmPLrg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: rustfs-cnpg-cloud-token
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:kLHQ3gqS38bmYmg5Clr4nFlm+KU=,iv:BBgBDlWFFpf7jZwGMmVo+52aUD94uWfomXws1x8Xv2g=,tag:rUQ5anR+xd2A9p7Jap/RWQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:oMzRi5NtWE0XPXCksFYol2sBpbcFZt3D5DEvkjrc4aw1ZccfHErRlA==,iv:/yAkPiLKlLEe9sgBwZGWYxRhj3RdWhEwOQWzR+KLeeU=,tag:+tjXHlzfIW6K0iGDrnWdog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBM1NmSWRtT2xGN2F5TmVy
            OXpvUEZ3emtIdFV3cWFxWndGeURwYTBkSHdjCkpEWGFEa0FpSzVkNzVNQ2JRdVJw
            ZEJCOXlpUmpyY1dKSkJYbVlBQWhnT0UKLS0tIGpwNjd6eDJqckJSQUJJcXFoY1RC
            OXNsajQ5amx1NDIxbHZ1ZWFXamludW8KKxAI3NVLpBrUDrEUBNQsdSBQwcmemUhq
            pZFIX1+nfwsrG9wYyrn32uwSroCSVfW5rUyfdDWW0TqK/10yh0FTTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1878n4cfsfpjqquszn2tlj0kq8ckwhdyx5eqjl32rh5vfs265gydq4myw6a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T15:08:19Z"
    mac: ENC[AES256_GCM,data:iEHyrvRNjZo5+Bd1qVsNyh1fGb2UKFE5YbKI4kCDv7S/3x7Rmz1EqaJHGBu0U4p8IVduyQYbF1OpP9XCzj1OgmHlcylb2AkAUHp5eHXJzzzWBihcSVa5ACawSC+ZmFqB+GddsinYQLgun2aldlYoI4L0HPmd1ww0UyfzmKp5yH0=,iv:kKQKmGTusURW0i1S8RhOQ+3t3n6vUBpwOD8dTbrY6qU=,tag:8kCvD0oMuz1mDI0khmPLrg==,type:str]
    version: 3.13.1
