apiVersion: v1
kind: Secret
metadata:
    name: restic-hashicorp-vault-data
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:FduXQfEPWTsWBQ/i0rrl11PPrAudbgOU4nrZLw8I163jdDADbS0Ia2MJhY78LGG5o3aD/aEf+exw9/CMEp6F9Hnz28VgZMvwKeL7FaS3d2KWY9p9HYbY2F0JfvqWjGOPTzDJtpct01Q=,iv:UML1d6D95EVwVnixHWEFcAK/7TLfs92vSpmxSW9D/Iw=,tag:OfpalrNWUVVd4MXsAFDtPw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:ryyFbDTsLWnkbG5r,iv:rNQHWc3rU2OGsz3idzmKLahRMdw5sd9MnohfkNs3V3k=,tag:9Gcc7ceKLpychRDtgm0+ig==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JHh9eRZTb81Genuhmf0nz2ZBWHk=,iv:aHwboQ7iq+M9F5BLDER0JxpQda+Y/E813biOFbbp0lw=,tag:Qv4geBHvNMJlh5V5DdpWZw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:pXOpBNLWEtW6G3R19PkfXLGB7CAfjzgkKBTd/DGh/03AtrofSayntQ==,iv:raACUiN6IMcUIj4GBtyOQKWM2+GXOPYMx8sscFDX8xg=,tag:2z08+QHWRDnGcDU/yTbSog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SkZiMExhbHo0Zm5tUEwx
            NjNwWW9BaWpWaTZHVkZDeW14RitPeW1BczBBCldTNUY3QXUxUEFuUDVoSWFTRDdN
            RWhDRkxKK204N0xkU0V6RFpTWTNqUXcKLS0tIGxWMkFWMDhpc1RYZENWRzRRQ0Rk
            K21rUGlKVFZFSXZ6aWQ0b3hPZkNqSW8KrjTMcVfdjLtMgm0YVEo3bEMoR8vKUyYJ
            l/8oYgZjyggjVzeWrp9AY/JWhE1g6vMjXGXDTTkoPNiRsuJ5SWpnYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1878n4cfsfpjqquszn2tlj0kq8ckwhdyx5eqjl32rh5vfs265gydq4myw6a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T16:49:59Z"
    mac: ENC[AES256_GCM,data:r2DQlvQzqB9/7QrHVjIK9y0HCH3VZlxjNpqGgyPciJoDwCw1vSNu8ha/cQDVO/gYwrZNj4abTIoGa95vpLfUJS6zAOLdJ3V4QCYEy67jI7m+H3PUX3/1X9hihIOmC6axrSiTBszIcJvvA+1abGDFEosXG1LdnCWIuPmdF9nITus=,iv:Sy7oG60IjD5qcp+deVEEFGdqpRQeTs/XCaEYtl3wtBo=,tag:KatJ+GEIp6abdmWW8jHEgg==,type:str]
    version: 3.13.1
